<a href="https://colab.research.google.com/github/JayasreeThyadi/Co_War/blob/main/ML_Model_based_on_diseases.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Machine Learning Model to predict COVID using different Algorithms**

We used 4 different Algorithms to predict our results to check which one is the best model with **more accuracy**

Algorithms used here are:

1.   Gaussian Naive Bayes
2.   Decision Tree
3.   Random Forest
4.   Logistic Regression




In [ ]:
from google.colab import files
uplo = files.upload()



Saving covid_cleaned-3L.csv to covid_cleaned-3L.csv


## Import necessary packages

In [ ]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
%matplotlib inline
import time
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score,fbeta_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

from random import randint

## Read the Data

In [ ]:
df=pd.read_csv('covid_cleaned-3L.csv')
df=df.drop(['age'], axis = 1)
df=df.drop(['startage'], axis = 1)
df=df.drop(['age group'], axis = 1)
df=df.drop(['Unnamed: 20'], axis = 1)
df=df.drop(['patient_type'], axis = 1)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (20) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
df.head()

sex  pneumonia  age.1  ...  contact_other_covid  died  covid_res
0    0          0      3  ...                    0     0          1
1    1          0      4  ...                    1     0          1
2    1          0      3  ...                    1     0          1
3    1          0      3  ...                    0     0          1
4    1          0      4  ...                    1     0          1

[5 rows x 16 columns]

## No.of Rows and Columns

In [ ]:
df.shape

(346017, 16)

## Split the dataset into train data and test data

In [ ]:
# Split dataset in training and test datasets. in this X_train, X_test,are testing related feature set and label set. y_train, y_test are testing feature set and label set
size=df.shape[0]
testsize=0.4
print("test size of records", testsize)
X_train, X_test, y_train, y_test = train_test_split(df.drop(['covid_res'], axis=1), df['covid_res'], test_size=testsize)



test size of records 0.4


Test data is 10% of the overall dataset

## List down the different features(Independent variables)

In [ ]:
used_features = ["sex	",
                     "patient_type	",
                     "pneumonia",
                     "age.1",
                 	"diabetes",
                 "copd",
                 "asthma",	"inmsupr",	"hypertension",	"other_disease",	"cardiovascular",	"obesity","renal_chronic",	"tobacco",
                 "contact_other_covid","died"]




## Cleaning the dataset

In [ ]:
X_test.fillna(X_test.mean())

sex  pneumonia  age.1  ...  tobacco  contact_other_covid  died
2622      0          0      3  ...        0                    1     0
334760    0          0      4  ...        0                    0     0
306017    1          1      1  ...        0                    0     0
127311    1          0      4  ...        0                    0     0
111363    0          0      4  ...        1                    0     0
...     ...        ...    ...  ...      ...                  ...   ...
258768    0          0      3  ...        0                    1     0
207126    0          0      5  ...        0                    0     0
46387     1          0      3  ...        0                    0     0
264227    1          0      4  ...        0                    1     0
319909    0          0      3  ...        0                    1     0

[138407 rows x 15 columns]

## **Gaussian Naive Bayes**

In [ ]:
gnb = GaussianNB()
# Train classifier
gnb.fit(X_train, y_train)
# predict using X_Test

y_pred = gnb.predict(X_test)
print(y_pred)
ypredlenth=len(y_pred)
print("Last person contacted covid or not", y_pred[ypredlenth-1])
print("Last but 1 person contacted covid or not", y_pred[ypredlenth - 2])
print("Last but 2 person contacted covid or not", y_pred[ypredlenth - 3])
# to know the lenght of predicted
print(len(y_pred))


[0 0 1 ... 0 1 0]
Last person contacted covid or not 0
Last but 1 person contacted covid or not 1
Last but 2 person contacted covid or not 0
138407


## Accuracy of Gaussian Naive Bayes

In [ ]:
 accuracyScore=round(accuracy_score(y_test,y_pred),2)
 confusion_matrix(y_test, y_pred)
 precisionScore= round(precision_score(y_test, y_pred),2)
 recallScore=round(recall_score(y_test, y_pred),2)
 f1Score=round(f1_score(y_test, y_pred),2)
 fbetaScore=round(fbeta_score(y_test, y_pred, beta=0.5, average='micro'),2)

 print("precisionScore", precisionScore)
 print("recallScore", recallScore)
 print("f1Score", f1Score)
 print("accuracyScore",accuracyScore)
 print("fbetaScore", fbetaScore)


precisionScore 0.59
recallScore 0.32
f1Score 0.42
accuracyScore 0.64
fbetaScore 0.64


## **Decision Tree**

In [ ]:
 #
dtc = DecisionTreeClassifier(max_depth=None, random_state=None)
dtc.fit(X_train, y_train)
# predict using X_Test
y_pred = dtc.predict(X_test)
print(y_pred)
ypredlenth = len(y_pred)
# print("Last Project Success or Fail", y_pred[ypredlenth-1])
# print("Last but 1 Project Success or Fail", y_pred[ypredlenth - 2])
# print("Last but 2 Project Success or Fail", y_pred[ypredlenth - 3])
# to know the lenght of predicted
# print(len(y_pred))

# now find out precision_score, recall_score, f1_score
# to build confusion matrix actual vs predicted
daccuracyScore = round(accuracy_score(y_test, y_pred),2)
confusion_matrix(y_test, y_pred)
dprecisionScore = round(precision_score(y_test, y_pred),2)
drecallScore = round(recall_score(y_test, y_pred),2)
df1Score = round(f1_score(y_test, y_pred),2)
dfbetaScore = round(fbeta_score(y_test, y_pred, beta=0.5, average='micro'),2)

print(daccuracyScore,dprecisionScore,drecallScore,df1Score,dfbetaScore)


[0 0 0 ... 0 0 0]
0.65 0.67 0.25 0.36 0.65


# **Random Forest**

In [ ]:
rfc = RandomForestClassifier(max_depth=None, random_state=None)
rfc.fit(X_train, y_train)
# predict using X_Test
y_pred = rfc.predict(X_test)
print(y_pred)
ypredlenth = len(y_pred)
# print("Last Project Success or Fail", y_pred[ypredlenth-1])
# print("Last but 1 Project Success or Fail", y_pred[ypredlenth - 2])
# print("Last but 2 Project Success or Fail", y_pred[ypredlenth - 3])
# to know the lenght of predicted
# print(len(y_pred))
# brining back to normal shape
# now find out precision_score, recall_score, f1_score
# to build confusion matrix actual vs predicted
raccuracyScore = round(accuracy_score(y_test, y_pred),2)
confusion_matrix(y_test, y_pred)
rprecisionScore = round(precision_score(y_test, y_pred),2)
rrecallScore = round(recall_score(y_test, y_pred),2)
rf1Score = round(f1_score(y_test, y_pred),2)
rfbetaScore = round(fbeta_score(y_test, y_pred, beta=0.5, average='micro'),2)

print(raccuracyScore, rprecisionScore, rrecallScore, rf1Score, rfbetaScore)


[0 0 0 ... 0 0 0]
0.65 0.66 0.25 0.37 0.65


# **Logistic Regression**

In [ ]:
lrs = LogisticRegression()
lrs.fit(X_train, y_train)
# predict using X_Test
y_pred = lrs.predict(X_test)
print(y_pred)
ypredlenth = len(y_pred)
# print("Last Project Success or Fail", y_pred[ypredlenth-1])
# print("Last but 1 Project Success or Fail", y_pred[ypredlenth - 2])
# print("Last but 2 Project Success or Fail", y_pred[ypredlenth - 3])
# to know the lenght of predicted
# print(len(y_pred))
# now find out precision_score, recall_score, f1_score
# to build confusion matrix actual vs predicted
laccuracyScore = round(accuracy_score(y_test, y_pred),2)
confusion_matrix(y_test, y_pred)
lprecisionScore = round(precision_score(y_test, y_pred),2)
lrecallScore = round(recall_score(y_test, y_pred),2)
lf1Score = round(f1_score(y_test, y_pred),2)
lfbetaScore = round(fbeta_score(y_test, y_pred, beta=0.5, average='micro'),2)
print(laccuracyScore, lprecisionScore, lrecallScore, lf1Score, lfbetaScore)

[1 1 0 ... 0 0 0]
0.65 0.68 0.26 0.37 0.65


## Trying to predict new projects sucess using this algorithm

In [ ]:
# trying to predict new projects sucess using this algorithm
testSet=[[[randint(0,1),randint(0,1),randint(0,1),randint(1,5),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),
randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1)]]]
#print(testSet[0][0][0])
print(testSet)
predTest=[]
predTest=testSet
testSetValues=[]
print("project scores are ")
newy_pred1 = lrs.predict(testSet[0])
testSetValues.append(newy_pred1[0])
print("lrs newy_pred", newy_pred1)
newy_pred1 = rfc.predict(testSet[0])
testSetValues.append(newy_pred1[0])
print("rfc newy_pred", newy_pred1)
newy_pred1 = gnb.predict(testSet[0])
testSetValues.append(newy_pred1[0])
print("gnb newy_pred", newy_pred1)
newy_pred1 = dtc.predict(testSet[0])
testSetValues.append(newy_pred1[0])
print("dtc newy_pred", newy_pred1)

[[[0, 1, 0, 5, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1]]]
project scores are 
lrs newy_pred [0]
rfc newy_pred [1]
gnb newy_pred [1]
dtc newy_pred [1]
