<a href="https://colab.research.google.com/github/JayasreeThyadi/Co_War/blob/main/ML_Model_basesd_on_Symptoms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Machine Learning Model to predict COVID using different Algorithms**

We used 4 different Algorithms to predict our results to check which one is the best model with **more accuracy**

Algorithms used here are:

1.   Gaussian Naive Bayes
2.   Decision Tree
3.   Random Forest
4.   Logistic Regression




In [ ]:
from google.colab import files
uplo = files.upload()



Saving DATASET_Symptoms_CovidPred.csv to DATASET_Symptoms_CovidPred (5).csv


## Import necessary packages

In [ ]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
%matplotlib inline
import time
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score,fbeta_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

from random import randint

## Read the Data

In [ ]:
df=pd.read_csv('DATASET_Symptoms_CovidPred (5).csv')
df.head()

EYE PAIN  ...  If you have been tested, did this test find that you had coronavirus (COVID-19)?
0         1  ...                                                  0                               
1         1  ...                                                  1                               
2         0  ...                                                  0                               
3         0  ...                                                  0                               
4         0  ...                                                  0                               

[5 rows x 32 columns]

## No.of Rows and Columns

In [ ]:
df.shape

(227, 32)

## Split the dataset into train data and test data

In [ ]:
# Split dataset in training and test datasets. in this X_train, X_test,are testing related feature set and label set. y_train, y_test are testing feature set and label set
size=df.shape[0]
testsize=0.1
print("test size of records", testsize)
X_train, X_test, y_train, y_test = train_test_split(df.drop(['If you have been tested, did this test find that you had coronavirus (COVID-19)?'], axis=1), df['If you have been tested, did this test find that you had coronavirus (COVID-19)?'], test_size=testsize)
# Instantiate the classifier GaussianNB


test size of records 0.1


Test data is 10% of the overall dataset

## List down the different features(Independent variables)

In [ ]:
used_features = ["EYE PAIN",
                     "CHEST PAIN",
                     "SOAR THROAT",
                     "STUFFY/RUNNY 0SE",
                     "WEAKNESS FATIGUE",
                     "Aches/ Muscle Pain",
                     "Headache",
                     "Cough",
                     "Difficulty in Breathing",
                     "Change in Sleep Cycle",
                     "Do you personally k0w anyone in your local community who is ill with a fever and either a cough or difficulty breathing?",
                     "Have you ever been tested for coronavirus (COVID-19)?	",
                     "Have you been tested for coronavirus (COVID-19) in the last 14 days?",
                     "HAVE YOU EVER BEEN SUFFERED WITH THE BELOW MENTIONED DISEASES (OR) ARE YOU SUFFURING FROM ANY OF THE DISEASES BELOW.",
                     "In the last 24 hours, have you done any of the following? [Have gone to work outside that place where you live]",
                     "In the last 24 hours, have you done any of the following? [Gone to Supermarket or Pharmacy]",
                     "In the last 24 hours, have you done any of the following? [Gone to Restaurant/CAFE/Shopping Center]	",
                     "In the last 24 hours, have you done any of the following? [Spent time with someone who is currently not staying with you.]",
                     "In the last 24 hours, have you done any of the following? [Attended public meet with more than 10 people]	",
                     "In the last 24 hours, have you done any of the following? [You were present in the crowded place of more than 7 people]	",
                     "In the last 24 hours, have you done any of the following? [Have used Public Transport]",
                     "In the last 24 hours, have you done any of the following? [You were at Home.]",
                     "In the last 24 hours, have you done any of the following? [None of the above]",
                    "In last 24 Hours When Ever you stepped outside your personal premises, How 3 have you used mask/face cover.",
                 "How are you intentionally avoiding contact with other people?",
                 "GENDER",
                 "DO YOU SMOKE ?",
                 "ALCHOHOL CONSUMPTION",
                 "Do you access to Sanitizer/Hand wash at workplace",
                 "Do you access to Sanitizer/Hand wash at Home",
                 "AGE BAND"]





## Cleaning the dataset

In [ ]:
X_test.fillna(X_test.mean())

EYE PAIN  ...  AGE BAND
90          0  ...         0
86          1  ...         0
113         0  ...         0
84          0  ...         0
44          0  ...         0
175         0  ...         0
70          0  ...         0
69          0  ...         1
142         0  ...         0
167         0  ...         0
147         1  ...         0
145         0  ...         0
164         0  ...         0
220         0  ...         0
202         0  ...         0
16          0  ...         0
34          0  ...         0
39          0  ...         0
187         0  ...         0
2           0  ...         2
62          0  ...         0
118         0  ...         0
24          0  ...         0

[23 rows x 31 columns]

## **Gaussian Naive Bayes**

In [ ]:
gnb = GaussianNB()
# Train classifier
gnb.fit(X_train, y_train)
# predict using X_Test

y_pred = gnb.predict(X_test)
print(y_pred)
ypredlenth=len(y_pred)
print("Last person contacted covid or not", y_pred[ypredlenth-1])
print("Last but 1 person contacted covid or not", y_pred[ypredlenth - 2])
print("Last but 2 person contacted covid or not", y_pred[ypredlenth - 3])
# to know the lenght of predicted
print(len(y_pred))


[1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
Last person contacted covid or not 1
Last but 1 person contacted covid or not 1
Last but 2 person contacted covid or not 1
23


## Accuracy of Gaussian Naive Bayes

In [ ]:
 accuracyScore=round(accuracy_score(y_test,y_pred),2)
 confusion_matrix(y_test, y_pred)
 precisionScore= round(precision_score(y_test, y_pred),2)
 recallScore=round(recall_score(y_test, y_pred),2)
 f1Score=round(f1_score(y_test, y_pred),2)
 fbetaScore=round(fbeta_score(y_test, y_pred, beta=0.5, average='micro'),2)

 print("precisionScore", precisionScore)
 print("recallScore", recallScore)
 print("f1Score", f1Score)
 print("accuracyScore",accuracyScore)
 print("fbetaScore", fbetaScore)


precisionScore 0.1
recallScore 0.67
f1Score 0.17
accuracyScore 0.13
fbetaScore 0.13


Here, you can see that the acuuracy of Gaussian Naive Bayes is 13%

## **Decision Tree**

In [ ]:
 #
dtc = DecisionTreeClassifier(max_depth=None, random_state=None)
dtc.fit(X_train, y_train)
# predict using X_Test
y_pred = dtc.predict(X_test)
print(y_pred)
ypredlenth = len(y_pred)
# print("Last Project Success or Fail", y_pred[ypredlenth-1])
# print("Last but 1 Project Success or Fail", y_pred[ypredlenth - 2])
# print("Last but 2 Project Success or Fail", y_pred[ypredlenth - 3])
# to know the lenght of predicted
# print(len(y_pred))

# now find out precision_score, recall_score, f1_score
# to build confusion matrix actual vs predicted
daccuracyScore = round(accuracy_score(y_test, y_pred),2)
confusion_matrix(y_test, y_pred)
dprecisionScore = round(precision_score(y_test, y_pred),2)
drecallScore = round(recall_score(y_test, y_pred),2)
df1Score = round(f1_score(y_test, y_pred),2)
dfbetaScore = round(fbeta_score(y_test, y_pred, beta=0.5, average='micro'),2)

print(daccuracyScore,dprecisionScore,drecallScore,df1Score,dfbetaScore)


[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
0.83 0.0 0.0 0.0 0.83


Here you can see that the accuracy of Decision Tree is 83%

# **Random Forest**

In [ ]:
rfc = RandomForestClassifier(max_depth=None, random_state=None)
rfc.fit(X_train, y_train)
# predict using X_Test
y_pred = rfc.predict(X_test)
print(y_pred)
ypredlenth = len(y_pred)
# print("Last Project Success or Fail", y_pred[ypredlenth-1])
# print("Last but 1 Project Success or Fail", y_pred[ypredlenth - 2])
# print("Last but 2 Project Success or Fail", y_pred[ypredlenth - 3])
# to know the lenght of predicted
# print(len(y_pred))
# brining back to normal shape
# now find out precision_score, recall_score, f1_score
# to build confusion matrix actual vs predicted
raccuracyScore = round(accuracy_score(y_test, y_pred),2)
confusion_matrix(y_test, y_pred)
rprecisionScore = round(precision_score(y_test, y_pred),2)
rrecallScore = round(recall_score(y_test, y_pred),2)
rf1Score = round(f1_score(y_test, y_pred),2)
rfbetaScore = round(fbeta_score(y_test, y_pred, beta=0.5, average='micro'),2)

print(raccuracyScore, rprecisionScore, rrecallScore, rf1Score, rfbetaScore)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
0.87 0.0 0.0 0.0 0.87


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Here you can see that the accuracy of Random Forest is 87%

# **Logistic Regression**

In [ ]:
lrs = LogisticRegression()
lrs.fit(X_train, y_train)
# predict using X_Test
y_pred = lrs.predict(X_test)
print(y_pred)
ypredlenth = len(y_pred)
# print("Last Project Success or Fail", y_pred[ypredlenth-1])
# print("Last but 1 Project Success or Fail", y_pred[ypredlenth - 2])
# print("Last but 2 Project Success or Fail", y_pred[ypredlenth - 3])
# to know the lenght of predicted
# print(len(y_pred))
# now find out precision_score, recall_score, f1_score
# to build confusion matrix actual vs predicted
laccuracyScore = round(accuracy_score(y_test, y_pred),2)
confusion_matrix(y_test, y_pred)
lprecisionScore = round(precision_score(y_test, y_pred),2)
lrecallScore = round(recall_score(y_test, y_pred),2)
lf1Score = round(f1_score(y_test, y_pred),2)
lfbetaScore = round(fbeta_score(y_test, y_pred, beta=0.5, average='micro'),2)
print(laccuracyScore, lprecisionScore, lrecallScore, lf1Score, lfbetaScore)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
0.87 0.0 0.0 0.0 0.87


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Here you can see that the accuracy of Logistic Regression is 87%

## Trying to predict new projects sucess using this algorithm

In [ ]:
# trying to predict new projects sucess using this algorithm
testSet=[[[randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(1,3),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,4),randint(0,4),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,1),randint(0,2)]]]
#print(testSet[0][0][0])
predTest=[]
predTest=testSet
testSetValues=[]
print("project scores are ")
newy_pred1 = lrs.predict(testSet[0])
testSetValues.append(newy_pred1[0])
print("lrs newy_pred", newy_pred1)
newy_pred1 = rfc.predict(testSet[0])
testSetValues.append(newy_pred1[0])
print("rfc newy_pred", newy_pred1)
newy_pred1 = gnb.predict(testSet[0])
testSetValues.append(newy_pred1[0])
print("gnb newy_pred", newy_pred1)
newy_pred1 = dtc.predict(testSet[0])
testSetValues.append(newy_pred1[0])
print("dtc newy_pred", newy_pred1)

project scores are 
lrs newy_pred [0]
rfc newy_pred [0]
gnb newy_pred [1]
dtc newy_pred [1]
